# Generated by Django 5.0 on 2023-12-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Post',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Posts',
        ),
    ]
